var state = { products:{}, orders:[], logs:[], me:null };
function $(id){ return document.getElementById(id); }
function money(n){ return '৳' + Number(n||0).toLocaleString('bn-BD'); }
function toast(msg,type){ var t=$('toast'); if(!t)return; t.textContent=msg; t.className='toast '+(type||'success')+' show'; setTimeout(()=>t.classList.remove('show'),3000); }
async function api(url,opt){ opt=opt||{}; opt.credentials='include'; opt.headers=opt.headers||{'Content-Type':'application/json'}; var r=await fetch(url,opt); if(r.status===401&&!url.includes('/login')){showLogin(); throw new Error('unauthorized');} return r; }
function showLogin(){ $('loginView').classList.remove('hidden'); $('dashboardView').classList.add('hidden'); }
function showDash(){ $('loginView').classList.add('hidden'); $('dashboardView').classList.remove('hidden'); }
async function login(){ var r=await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:$('usernameInput').value.trim(),password:$('passwordInput').value})}); var d=await r.json(); if(d.success){showDash(); await loadDashboard(); toast('Logged in securely');} else {$('loginError').textContent=d.error||'Login failed';} }
async function logout(){ try{await api('/api/admin/logout',{method:'POST'});}catch(e){} showLogin(); }
async function boot(){ try{var r=await api('/api/admin/me'); if(r.ok){showDash(); await loadDashboard();} else showLogin();}catch(e){showLogin();} }
async function loadDashboard(){ var r=await api('/api/admin/dashboard'); var d=await r.json(); state.products=d.products; state.orders=d.orders; state.logs=d.logs; $('storageStatus').textContent='DATA_DIR: '+d.dataDir+' — Render persistent disk ready'; renderStats(); renderForms(); renderOrders(); renderLogs(); }
function renderStats(){ var o=state.orders, rev=o.filter(x=>x.status!=='cancelled').reduce((s,x)=>s+(x.totalPrice||0),0); $('statOrders').textContent=o.length; $('statRevenue').textContent=money(rev); $('statBkash').textContent=o.filter(x=>x.paymentMethod==='bkash').length; $('statNagad').textContent=o.filter(x=>x.paymentMethod==='nagad').length; var statuses=['new','confirmed','delivered','cancelled']; $('analyticsBars').innerHTML=statuses.map(st=>{var c=o.filter(x=>x.status===st).length,p=o.length?Math.max(5,c/o.length*100):5;return '<div class="barline"><span>'+st+'</span><b><i style="width:'+p+'%"></i></b><strong>'+c+'</strong></div>';}).join(''); $('paymentMix').innerHTML='<div class="paychip">Txnid Checked <b>'+o.filter(x=>x.transactionId).length+'</b></div><div class="paychip">bKash <b>'+$('statBkash').textContent+'</b></div><div class="paychip">Nagad <b>'+$('statNagad').textContent+'</b></div>'; }
function productForm(id){ var p=state.products[id]; return '<div class="admin-card"><h2>'+(id==='mango'?'🥭 Mango Management':'🍒 Litchi Management')+'</h2><div class="form-grid"><label>Name<input id="'+id+'Name" value="'+p.name+'"></label><label>English<input id="'+id+'English" value="'+p.englishName+'"></label><label>Price<input type="number" id="'+id+'Price" value="'+p.price+'"></label><label>Badge<input id="'+id+'Badge" value="'+p.badge+'"></label><label>Min Qty<input type="number" id="'+id+'Min" value="'+p.minQty+'"></label><label>Max Qty<input type="number" id="'+id+'Max" value="'+p.maxQty+'"></label></div><label>Description<textarea id="'+id+'Desc">'+p.description+'</textarea></label><label class="check"><input type="checkbox" id="'+id+'Stock" '+(p.stock?'checked':'')+'> In Stock</label><button onclick="saveProduct(\''+id+'\')">Save '+id+'</button><div class="upload-box"><input type="file" id="'+id+'Image" accept="image/*"><button onclick="uploadImage(\''+id+'\')">Upload Product Image</button></div><div class="admin-images">'+(p.images||[]).map(img=>'<div><img src="'+img.url+'"><label><input type="checkbox" '+(img.showInSlider?'checked':'')+' onchange="toggleImage(\''+id+'\',\''+img.id+'\',this.checked)"> Slider</label><button onclick="deleteImage(\''+id+'\',\''+img.id+'\')">Delete</button></div>').join('')+'</div></div>'; }
function renderForms(){ $('mangoForm').innerHTML=productForm('mango'); $('litchiForm').innerHTML=productForm('litchi'); }
async function saveProduct(id){ var body={name:$(id+'Name').value,englishName:$(id+'English').value,price:+$(id+'Price').value,badge:$(id+'Badge').value,minQty:+$(id+'Min').value,maxQty:+$(id+'Max').value,description:$(id+'Desc').value,stock:$(id+'Stock').checked}; var r=await api('/api/admin/products/'+id,{method:'PUT',body:JSON.stringify(body)}); var d=await r.json(); state.products=d.products; renderForms(); toast('Product saved permanently'); await refreshLogs(); }
function fileData(file){ return new Promise((res,rej)=>{var rd=new FileReader(); rd.onload=()=>res(rd.result); rd.onerror=rej; rd.readAsDataURL(file);}); }
async function uploadImage(id){ var input=$(id+'Image'); if(!input.files[0]) return toast('Select an image','error'); var dataUrl=await fileData(input.files[0]); var r=await api('/api/admin/products/'+id+'/images',{method:'POST',body:JSON.stringify({name:input.files[0].name,dataUrl:dataUrl,showInSlider:true})}); if(!r.ok)return toast('Upload failed','error'); await loadDashboard(); toast('Image uploaded to persistent disk'); }
async function toggleImage(pid,iid,checked){ await api('/api/admin/products/'+pid+'/images/'+iid,{method:'PATCH',body:JSON.stringify({showInSlider:checked})}); await loadDashboard(); }
async function deleteImage(pid,iid){ if(confirm('Delete image?')){ await api('/api/admin/products/'+pid+'/images/'+iid,{method:'DELETE'}); await loadDashboard(); } }
function renderOrders(){ $('orderList').innerHTML=state.orders.map(o=>'<div class="admin-order"><div><strong>#'+o.id+'</strong><p>'+o.customerName+' • '+o.phone+'</p><small>'+o.items.map(i=>i.name+' × '+i.qty).join(', ')+'</small></div><div><b>'+money(o.totalPrice)+'</b><small>'+o.paymentName+'<br>Txnid: '+o.transactionId+'</small><select onchange="setStatus(\''+o.id+'\',this.value)"><option '+(o.status==='new'?'selected':'')+' value="new">new</option><option '+(o.status==='confirmed'?'selected':'')+' value="confirmed">confirmed</option><option '+(o.status==='delivered'?'selected':'')+' value="delivered">delivered</option><option '+(o.status==='cancelled'?'selected':'')+' value="cancelled">cancelled</option></select></div></div>').join('')||'<div class="admin-card">No orders yet.</div>'; }
async function setStatus(id,status){ await api('/api/admin/orders/'+id,{method:'PATCH',body:JSON.stringify({status})}); await loadDashboard(); toast('Order updated'); }
async function refreshLogs(){ var r=await api('/api/admin/logs'); state.logs=await r.json(); renderLogs(); }
function renderLogs(){ $('logViewer').innerHTML=state.logs.map(l=>'<div class="log-row"><div><strong>'+l.message+'</strong><small>'+new Date(l.createdAt).toLocaleString()+'</small></div><code>'+l.type+'</code><span>'+(l.meta.transactionId?'Txnid: '+l.meta.transactionId:'')+'</span></div>').join('')||'<div class="admin-card">No logs yet.</div>'; }
function switchAdminTab(tab){ document.querySelectorAll('.admin-sidebar button').forEach(b=>b.classList.remove('active')); event.target.classList.add('active'); document.querySelectorAll('.admin-tab').forEach(t=>t.classList.remove('active')); $('tab'+tab.charAt(0).toUpperCase()+tab.slice(1)).classList.add('active'); if(tab==='logs')refreshLogs(); }
setInterval(()=>{ if(!$('dashboardView').classList.contains('hidden')) loadDashboard(); },30000);
boot();
